apiVersion: v1
kind: Namespace
metadata:
  name: default
spec:
  finalizers:
    - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ctseorderervice
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ctseorderervice
    template:
      metadata:
        labels:
          app: ctseorderervice
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: ctseorderervice
            image: minindukothalawala/ctseorderervice
            ports:
              - containerPort: 8080
            resources:
              requests:
                cpu: '2'
                memory: '100'
              limits:
                cpu: '256'
                memory: 11400G
