apiVersion: v1
kind: Service
metadata:
  name: ctseorderervice-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: ctseorderervice
