apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ctsemicroservice-ef2e"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ctsemicroservice-ef2e"
  template:
    metadata:
      labels:
        app: "ctsemicroservice-ef2e"
    spec:
      containers:
        - name: "ctsemicroservice-ef2e"
          image: "ctsemicroservicenew.azurecr.io/ctsemicroservice"
          ports:
          - containerPort: 8080