# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - CTSE-Microservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ctsemicroservice.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3f099b26f3314715bd9522d0f5084805 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cf8b9f9cd014465397367ab06ff359f5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ctsemicroservice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3f099b26f3314715bd9522d0f5084805 }}/order-service-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CTSE-Microservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e86ec476e17d4f42959c2716148430b6 }}
        images: 'ctsemicroservice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3f099b26f3314715bd9522d0f5084805 }}/order-service-dev:${{ github.sha }}'